### ISSUE TITLE
Is there any documentation how to use it ?

### ISSUE THREAD

**Issue by flashultra** [ShaharMS/texter#10]
I want to try RTL for OpenFL , but  for TextFieldRTL.hx have message "Deprecated - Will get removed in later version due to buggy behavior".
I'm not sure what is the use of  DynamicTextField.hx . Should I use this for RTL ?
There are some classes in the `general` package, but I don't know how to use them.
Emoji class looks interesting, but support only char emoji. Is is possible to support image ( bitmap ) emojis ?
I will appreciate any example how to use the project for RTL .

Thank you

**Comment by ShaharMS** [comment]
I think I'll go one by one:

 - `TextFieldRTL` was supposed to be a version of textfield that supports RTL. After a release or two of trying to fix a bunch of bugs relating to selection, I've decided it would be better for everyone to work on something else, and deprecated this class.
 - `DynamicTextField` is a special text field that has controls, allowing you to drag, resize or rotate it. It doesn't have any special bidi things.
 - the `general subfolder contains things that dont have to relate to a specific framework - such as the markdown -> ast parser, or the emoji maps`

If you just want BiDi support in your project, you can do:

```haxe
using BidiTools;

...
textfielf.attachBidifier(); //can be TextField, DynamicTextField, TextFieldRTL 
```

**Comment by ShaharMS** [comment]
Once the live BiDi engine works well enough, and I reorganize it, I might repurpose TextFieldRTL to just extend `TextField` and have the bidi algorithm work on that class. That should be soon.

BTW, are you using texter from git, or haxelib?

**Comment by flashultra** [comment]
First I was using the haxelib version, but then I updated to Git.
 I think the above information should be included in the README, it will give a head start for someone who wants to try the texter lib.
 I will close this  issue.

**Comment by ShaharMS** [comment]
youre right, i should include something like the list above in the readme. technically, the haxelib version should always have up-to-date features and bugfixes, and only WIP stuff stays in git. im working on a bunch of things rn so that isnt really happening, but should happen in the near future (probably afte release 2.4.0)
